server:
  port: 8000
  servlet:
    contextPath: /api/v1
    session:
      cookie:
        path: / # 적용될 URL 경로를 나타냄. 해당 도메인의 모든 경로에서 쿠키가 사용.
        name: ${.session.name} # 이름을 지정.
        domain: ${.session.domain} # 유효 도메인을 지정. 해당 도메인과 그 서브도메인에서 쿠키가 유효
        http-only: true # 브라우저에서 해당 쿠키에 대한 JavaScript 접근을 제한합니다. 이를 통해 XSS 공격을 방지할 수 있습니다.
        secure: false # HTTPS 연결을 통해서만 전송 가능.
        max-age: 1209600 # 쿠키의 유효 시간을 초 단위로 설정.
      timeout: 1209600 # 세션 타임아웃 시간을 초 단위로 설정..

management:
  endpoints:
    web:
      exposure:
        include: prometheus

spring:
  application:
    name: oDuckio
  config:
    activate:
      on-profile: local
    import :  'aws-parameterstore:/config/oDuckio_local'
  cloud:
    aws:
      parameterstore:
        region: ${aws_region}
      credentials:
        access-key: ${aws_access_key}
        secret-key: ${aws_secret_key}
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${.db.host}:${.db.port}/${.db.name}?useSSL=false&serverTimezone=UTC
    username: ${.db.username}
    password: ${.db.password}
  data:
    redis:
      host: localhost
      port: ${.redis.port}
      repositories:
        enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${.oauth2.google.client.id}
            client-secret: ${.oauth2.google.client.secret}
            scope: profile, email
            redirect-uri: ${.oauth2.google.redirect.url}

          naver:
            client-id: ${.oauth2.naver.client.id}
            client-secret: ${.oauth2.naver.client.secret}
            redirect-uri: ${.oauth2.naver.redirect.url}
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver

          kakao:
            client-id: ${.oauth2.kakao.client.id}
            client-secret: ${.oauth2.kakao.client.secret}
            redirect-uri: ${.oauth2.kakao.redirect.url}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    root: INFO
  file:
    name: ./logs/oDuck.log
  logback:
    rollingpolicy:
      max-file-size: 10MB   #default 10MB
      max-history: 30       #default 7
      file-name-pattern: ./logs/oDuck.%d{yyyy-MM-dd}.%i.gz

config:
  base:
    url: ${.base.url}
  webhook:
    url: ${.webhook.url}qza3xc3efqdx
