server:
  port: 8000
  servlet:
    contextPath:
    session:
      cookie:
        path:
        name:
        domain:
        http-only:
        secure:
      timeout:

spring:
  config:
    activate:
      on-profile:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  data:
    redis:
      host:
      port: 6379
      session:
        store-type: redis
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile, email
            redirect-uri:

          naver:
            client-id:
            client-secret:
            redirect-uri:
            authorization-grant-type:
            scope: email
            client-name: Naver

          kakao:
            client-id:
            client-secret:
            redirect-uri:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri:
            token_uri:
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri:
            token-uri:
            user-info-uri:
            user-name-attribute: id

logging:
  level:
    root: INFO
  file:
    path:
    name:
  logback:
    rollingpolicy:
      max-file-size:
      max-history: 30       #default 7
      file-name-pattern:

config:
  base:
    url:
