global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'oDuckio'
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['spring:8000']
